/*
 * Simplified user API specification
 *
 * This openapi document describes user API.
 *
 * API version: 1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {
	Name string `json:"name,omitempty"`
	Identifier string `json:"identifier,omitempty"`
}
