/*
 * Simplified user API specification
 *
 * This openapi document describes user API.
 *
 * API version: 1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"BanUser",
		strings.ToUpper("Post"),
		"/users/{username}/ban",
		BanUser,
	},

	Route{
		"CommentPhoto",
		strings.ToUpper("Post"),
		"/photos/{id}/comments",
		CommentPhoto,
	},

	Route{
		"DeletePhoto",
		strings.ToUpper("Delete"),
		"/photos/{id}",
		DeletePhoto,
	},

	Route{
		"FollowUser",
		strings.ToUpper("Post"),
		"/users/{username}/follow",
		FollowUser,
	},

	Route{
		"GetMyStream",
		strings.ToUpper("Get"),
		"/",
		GetMyStream,
	},

	Route{
		"LikePhoto",
		strings.ToUpper("Post"),
		"/photos/{id}",
		LikePhoto,
	},

	Route{
		"DoLogin",
		strings.ToUpper("Post"),
		"/session",
		DoLogin,
	},

	Route{
		"SetMyUserName",
		strings.ToUpper("Put"),
		"/myProfile",
		SetMyUserName,
	},

	Route{
		"UnbanUser",
		strings.ToUpper("Delete"),
		"/users/{username}/ban",
		UnbanUser,
	},

	Route{
		"UncommentPhoto",
		strings.ToUpper("Delete"),
		"/photos/{id}/comments",
		UncommentPhoto,
	},

	Route{
		"UnfollowUser",
		strings.ToUpper("Delete"),
		"/users/{username}/follow",
		UnfollowUser,
	},

	Route{
		"UnlikePhoto",
		strings.ToUpper("Put"),
		"/photos/{id}",
		UnlikePhoto,
	},

	Route{
		"UploadPhoto",
		strings.ToUpper("Post"),
		"/photos",
		UploadPhoto,
	},

	Route{
		"GetUsers",
		strings.ToUpper("Get"),
		"/users",
		GetUsers,
	},

	Route{
		"GetUserProfile",
		strings.ToUpper("Get"),
		"/users/{username}",
		GetUserProfile,
	},
}
